"""
PostgreSQL / Supabase connector.

Handles:
- Initializing the Supabase client
- Upserting scraped CreditCard records
- Executing dynamic SQL filter queries built by the RAG router
"""

from __future__ import annotations

import logging
import os
from typing import Any

from dotenv import load_dotenv
from pydantic import ValidationError
from supabase import create_client, Client

from app.models import CreditCard

load_dotenv()
log = logging.getLogger("db")

# SQL DDL — run once against your Supabase project (see docs/schema.sql)
SCHEMA_DDL = """
CREATE TABLE IF NOT EXISTS credit_cards (
    id                      SERIAL PRIMARY KEY,
    name                    TEXT NOT NULL,
    issuer                  TEXT NOT NULL,
    annual_fee              NUMERIC(10, 2) NOT NULL DEFAULT 0,
    regular_apr_low         NUMERIC(5, 2)  NOT NULL DEFAULT 0,
    regular_apr_high        NUMERIC(5, 2)  NOT NULL DEFAULT 0,
    signup_bonus            TEXT,
    signup_bonus_value_usd  NUMERIC(10, 2) DEFAULT 0,
    travel_multiplier       NUMERIC(4, 2)  DEFAULT 1.0,
    dining_multiplier       NUMERIC(4, 2)  DEFAULT 1.0,
    groceries_multiplier    NUMERIC(4, 2)  DEFAULT 1.0,
    gas_multiplier          NUMERIC(4, 2)  DEFAULT 1.0,
    online_shopping_mult    NUMERIC(4, 2)  DEFAULT 1.0,
    other_multiplier        NUMERIC(4, 2)  DEFAULT 1.0,
    lounge_access           BOOLEAN        DEFAULT FALSE,
    foreign_transaction_fee NUMERIC(4, 2)  DEFAULT 0,
    credit_score_required   TEXT           DEFAULT 'Good',
    source_url              TEXT,
    description             TEXT,
    created_at              TIMESTAMPTZ    DEFAULT NOW(),
    updated_at              TIMESTAMPTZ    DEFAULT NOW(),
    UNIQUE(name, issuer)
);

-- Trigger to keep updated_at fresh
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$;

DROP TRIGGER IF EXISTS trg_cards_updated_at ON credit_cards;
CREATE TRIGGER trg_cards_updated_at
    BEFORE UPDATE ON credit_cards
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();
"""


def get_client() -> Client:
    """Return an authenticated Supabase client. Raises if env vars are missing."""
    url = os.environ.get("SUPABASE_URL")
    key = os.environ.get("SUPABASE_ANON_KEY")
    if not url or not key:
        raise EnvironmentError(
            "SUPABASE_URL and SUPABASE_ANON_KEY must be set in your .env file."
        )
    return create_client(url, key)


def _card_to_row(card: CreditCard) -> dict[str, Any]:
    """Flatten a CreditCard Pydantic model into a flat DB row dict."""
    m = card.reward_multipliers
    return {
        "name": card.name,
        "issuer": card.issuer,
        "annual_fee": card.annual_fee,
        "regular_apr_low": card.regular_apr_low,
        "regular_apr_high": card.regular_apr_high,
        "signup_bonus": card.signup_bonus,
        "signup_bonus_value_usd": card.signup_bonus_value_usd,
        "travel_multiplier": m.travel,
        "dining_multiplier": m.dining,
        "groceries_multiplier": m.groceries,
        "gas_multiplier": m.gas,
        "online_shopping_mult": m.online_shopping,
        "other_multiplier": m.other,
        "lounge_access": card.lounge_access,
        "foreign_transaction_fee": card.foreign_transaction_fee,
        "credit_score_required": card.credit_score_required,
        "source_url": card.source_url,
        "description": card.description,
    }


def upsert_cards(cards: list[CreditCard]) -> list[dict[str, Any]]:
    """
    Upsert a batch of CreditCard objects into Supabase.
    Conflict resolution is on (name, issuer) — updates existing records.
    Returns the upserted rows.
    """
    if not cards:
        return []

    client = get_client()
    rows = [_card_to_row(c) for c in cards]

    try:
        response = (
            client.table("credit_cards")
            .upsert(rows, on_conflict="name,issuer")
            .execute()
        )
        log.info("Upserted %d card(s) to Supabase", len(rows))
        return response.data
    except Exception as exc:  # noqa: BLE001
        log.error("Supabase upsert failed: %s", exc)
        raise


def query_cards_by_filter(where_clause: str, limit: int = 20) -> list[dict[str, Any]]:
    """
    Execute a parameterised query against credit_cards using a WHERE clause
    fragment generated by the intent router.

    The where_clause is appended to a safe base query via Supabase's PostgREST
    filter syntax. For complex clauses we fall back to a raw RPC call.

    Example where_clause produced by router:
        "annual_fee.lte.100,lounge_access.eq.true"
    This uses Supabase's column.operator.value filter chaining.
    """
    client = get_client()

    try:
        query = client.table("credit_cards").select("*")

        # where_clause is a comma-separated list of "column.op.value" triples
        for condition in where_clause.split(","):
            condition = condition.strip()
            if not condition:
                continue
            parts = condition.split(".", 2)
            if len(parts) != 3:
                log.warning("Skipping malformed filter condition: %s", condition)
                continue
            col, op, val = parts
            # Type-cast numeric strings
            typed_val: Any = val
            try:
                typed_val = float(val)
            except ValueError:
                if val.lower() == "true":
                    typed_val = True
                elif val.lower() == "false":
                    typed_val = False

            query = query.filter(col, op, typed_val)

        response = query.limit(limit).execute()
        log.info(
            "SQL query returned %d row(s) for filter: %s",
            len(response.data),
            where_clause,
        )
        return response.data

    except Exception as exc:  # noqa: BLE001
        log.error("Supabase query failed for filter '%s': %s", where_clause, exc)
        raise


def get_all_cards(limit: int = 500) -> list[dict[str, Any]]:
    """Fetch all cards — used to rebuild the FAISS index from the DB."""
    client = get_client()
    response = client.table("credit_cards").select("*").limit(limit).execute()
    return response.data
